#! /bin/bash

echo "Killing current server workers"

# killing the master and workers
kill -9 $(lsof -t -i:8000)
kill -9 $(lsof -t -i:9000)

echo "Removing old jar and logs"
# cleaning up directories (tables, jars)
# rm -rf worker*/*.table # this removes ALL tables!!!!
# rm server_log
rm __worker*.jar
rm job*.jar
rm *log*

echo "Starting new server and workers"
# restarting master and workers
java -cp bin kvs.Master 8000 & 
java -cp bin flame.FlameMaster 9000 localhost:8000 & 

sleep 1

java -cp bin kvs.Worker 8001 worker1 localhost:8000 & 
java -cp bin kvs.Worker 8002 worker2 localhost:8000 &
java -cp bin kvs.Worker 8003 worker3 localhost:8000 &
java -cp bin kvs.Worker 8004 worker4 localhost:8000 &
java -cp bin kvs.Worker 8005 worker5 localhost:8000 &

java -cp bin flame.FlameWorker 9001 localhost:9000 &
# java -cp bin flame.FlameWorker 9002 localhost:9000 &
# java -cp bin flame.FlameWorker 9003 localhost:9000 &
# java -cp bin flame.FlameWorker 9004 localhost:9000 &
# java -cp bin flame.FlameWorker 9005 localhost:9000 &

echo "Ready! Please invoke job, such as java -cp bin flame.FlameSubmit localhost:9000 crawler.jar jobs.Crawler http://simple.crawltest.cis5550.net/"

# you need three clean terminals, A, B, C
# in terminal A under the backslashr-backend/ run ./abc
# this will kill existing server and kvs and delete files, see above
# then start server and worker

# now kick off crawler in terminal C

# now you want to restart everything, because C is done or have errors
# in terminal B under the backslashr-backend/ run ./abc
# this will kill whatever in terminal A and start things in terminal B

# now terminal A becomes B 

